language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install

script: make travis

notifications:
  webhooks:
    urls:
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true

after_script: make coveralls